package id.almezi.simplemoneytracker_kt

object TestTags {
    // Tambah / Edit Transaction screen
    const val TAMBAH_SCREEN = "tambah_screen"
    const val TAMBAH_TOGGLE_TYPE = "tambah_toggle_type"
    const val TAMBAH_INPUT_AMOUNT = "tambah_input_amount"
    const val TAMBAH_CATEGORY_PAGER = "tambah_category_pager"
    const val TAMBAH_CATEGORY_ITEM = "tambah_category_item"
    const val TAMBAH_CATEGORY_SEARCH = "tambah_category_search"
    const val TAMBAH_CATEGORY_SEARCH_EMPTY = "tambah_category_search_empty"
    const val TAMBAH_DATE_PICKER = "tambah_date_picker"
    const val TAMBAH_INPUT_NOTE = "tambah_input_note"
    const val TAMBAH_BUTTON_SAVE = "tambah_button_save"
    const val TAMBAH_ERROR_AMOUNT = "tambah_error_amount"
    const val TAMBAH_ERROR_CATEGORY = "tambah_error_category"
    const val TAMBAH_HEADER = "tambah_header"
    const val TAMBAH_SELECT_ACCOUNT = "tambah_select_account"
    const val TAMBAH_SELECT_DATE = "tambah_select_date"
    const val TAMBAH_HELPER = "tambah_helper"
    const val TAMBAH_LINK_KELOLA_KATEGORI = "tambah_link_kelola_kategori"
    const val TAMBAH_ACCOUNT_SHEET = "tambah_sheet_account"
    const val TAMBAH_ACCOUNT_ITEM = "tambah_account_item"

    // Daftar (list)
    const val DAFTAR_SCREEN = "daftar_screen"
    const val DAFTAR_ITEM = "daftar_item"
    const val DAFTAR_MONTH_SWITCHER = "daftar_month_switcher"
    const val DAFTAR_SUMMARY_MASUK = "daftar_summary_masuk"
    const val DAFTAR_SUMMARY_KELUAR = "daftar_summary_keluar"
    const val DAFTAR_BACKUP_BUTTON = "daftar_backup_button"
    const val DAFTAR_DAY_HEADER = "daftar_day_header"
    const val DAFTAR_EMPTY_STATE = "daftar_empty_state"

    // Anggaran (steps 7 and 8)
    const val ANGGARAN_SCREEN = "anggaran_screen"
    const val ANGGARAN_TOTAL_CARD = "anggaran_total_card"
    const val ANGGARAN_LIST = "anggaran_list"
    const val ANGGARAN_ROW = "anggaran_row"
    const val ANGGARAN_ADD_BUTTON = "anggaran_add_button"
    const val ANGGARAN_EMPTY_STATE = "anggaran_empty_state"
    const val ANGGARAN_FORM_SCREEN = "anggaran_form_screen"
    const val ANGGARAN_FORM_CATEGORY = "anggaran_form_category"
    const val ANGGARAN_FORM_LIMIT = "anggaran_form_limit"
    const val ANGGARAN_FORM_SWITCH = "anggaran_form_switch"
    const val ANGGARAN_FORM_NOTE = "anggaran_form_note"
    const val ANGGARAN_FORM_SAVE = "anggaran_form_save"
    const val ANGGARAN_FORM_DELETE = "anggaran_form_delete"
    const val ANGGARAN_DELETE_SHEET = "anggaran_delete_sheet"

    // Kelola kategori (step 9)
    const val KATEGORI_SCREEN = "kategori_screen"
    const val KATEGORI_TOGGLE_TYPE = "kategori_toggle_type"
    const val KATEGORI_ROW = "kategori_row"
    const val KATEGORI_ROW_EDIT = "kategori_row_edit"
    const val KATEGORI_ROW_HIDE = "kategori_row_hide"
    const val KATEGORI_ROW_DELETE = "kategori_row_delete"
    const val KATEGORI_ADD_BUTTON = "kategori_add_button"
    const val KATEGORI_HINT = "kategori_hint"
    const val KATEGORI_DELETE_SHEET = "kategori_delete_sheet"
    const val KATEGORI_FORM_SCREEN = "kategori_form_screen"
    const val KATEGORI_FORM_NAME = "kategori_form_name"
    const val KATEGORI_FORM_SWATCH = "kategori_form_swatch"
    const val KATEGORI_FORM_PREVIEW = "kategori_form_preview"
    const val KATEGORI_FORM_SAVE = "kategori_form_save"

    // Cadangan (step 10)
    const val CADANGAN_SCREEN = "cadangan_screen"
    const val CADANGAN_STATUS_CARD = "cadangan_status_card"
    const val CADANGAN_EXPORT_CSV = "cadangan_export_csv"
    const val CADANGAN_EXPORT_JSON = "cadangan_export_json"
    const val CADANGAN_IMPORT_BUTTON = "cadangan_import_button"
    const val CADANGAN_IMPORT_RESULT = "cadangan_import_result"
    const val CADANGAN_IMPORT_ERROR = "cadangan_import_error"
    const val CADANGAN_WARNING = "cadangan_warning"

    // Ubah transaksi
    const val UBAH_SCREEN = "ubah_screen"
    const val UBAH_HEADER = "ubah_header"
    const val UBAH_BUTTON_SAVE = "ubah_button_save"
    const val UBAH_BUTTON_DELETE = "ubah_button_delete"
    const val UBAH_DELETE_SHEET = "ubah_delete_sheet"

    // Ringkasan (summary)
    const val RINGKASAN_SCREEN = "ringkasan_screen"
    const val RINGKASAN_TOTALS_CARD = "ringkasan_totals_card"
    const val RINGKASAN_CATEGORY_ITEM = "ringkasan_category_item"
    const val RINGKASAN_MONTH_SWITCHER = "ringkasan_month_switcher"
    const val RINGKASAN_BALANCE_CARD = "ringkasan_balance_card"
    const val RINGKASAN_BALANCE_VALUE = "ringkasan_balance_value"
    const val RINGKASAN_SAVINGS_ROW = "ringkasan_savings_row"
    const val RINGKASAN_SAVINGS_VALUE = "ringkasan_savings_value"
    const val RINGKASAN_ANGGARAN_BUTTON = "ringkasan_anggaran_button"
    const val RINGKASAN_KELOLA_BUTTON = "ringkasan_kelola_button"
    const val RINGKASAN_COMPARISON = "ringkasan_comparison"
    const val RINGKASAN_BREAKDOWN_INCOME = "ringkasan_breakdown_income"
    const val RINGKASAN_BREAKDOWN_EXPENSE = "ringkasan_breakdown_expense"
    const val RINGKASAN_EMPTY_STATE = "ringkasan_empty_state"
    const val RINGKASAN_EMPTY_ACTION = "ringkasan_empty_action"

    // Shared design system components
    const val COMPONENT_BUTTON_PRIMARY = "component_button_primary"
    const val COMPONENT_BUTTON_SECONDARY = "component_button_secondary"
    const val COMPONENT_BUTTON_DESTRUCTIVE = "component_button_destructive"
    const val COMPONENT_BUTTON_TEXT_DANGER = "component_button_text_danger"
    const val COMPONENT_TOGGLE_SEGMENTED = "component_toggle_segmented"
    const val COMPONENT_INPUT_AMOUNT = "component_input_amount"
    const val COMPONENT_GRID_CATEGORY_CHIP = "component_grid_category_chip"
    const val COMPONENT_ROW_CATEGORY_CHIP = "component_row_category_chip"
    const val COMPONENT_FIELD_SELECT = "component_field_select"
    const val COMPONENT_FIELD_DATE = "component_field_date"
    const val COMPONENT_FIELD_NOTE = "component_field_note"
    const val COMPONENT_FIELD_SEARCH = "component_field_search"
    const val COMPONENT_SHEET_BOTTOM = "component_sheet_bottom"
    const val COMPONENT_SHEET_BUTTON_CONFIRM = "component_sheet_button_confirm"
    const val COMPONENT_SHEET_BUTTON_CANCEL = "component_sheet_button_cancel"
    const val COMPONENT_NAV_BOTTOM = "component_nav_bottom"
    const val COMPONENT_NAV_ITEM = "component_nav_item"
    const val COMPONENT_SWITCHER_MONTH = "component_switcher_month"
    const val COMPONENT_STATE_EMPTY = "component_state_empty"
    const val COMPONENT_SWITCH = "component_switch"
    const val COMPONENT_TOAST = "component_toast"
    const val COMPONENT_CARD_TRANSACTION = "component_card_transaction"
    const val COMPONENT_ROW_BUDGET = "component_row_budget"
    const val COMPONENT_PICKER_SHEET = "component_sheet_picker"
}
